import '@/api/http/auth-refresh'

export { api } from '@/api/http/client'
export * from '@/api/domains/auth'
export * from '@/api/domains/papers'
export * from '@/api/domains/library'
export * from '@/api/domains/integrations'
export * from '@/api/domains/scoring'
export * from '@/api/domains/projects'
export * from '@/api/domains/search'
export * from '@/api/domains/authors'
export * from '@/api/domains/analytics'
export * from '@/api/domains/reports'
export * from '@/api/domains/export'
export * from '@/api/domains/saved-searches'
export * from '@/api/domains/alerts'
export * from '@/api/domains/classification'
export * from '@/api/domains/groups'
export * from '@/api/domains/transfer'
export * from '@/api/domains/submissions'
export * from '@/api/domains/badges'
export * from '@/api/domains/knowledge'
export * from '@/api/domains/model-settings'
export * from '@/api/domains/developer'
export * from '@/api/domains/compliance'
export * from '@/api/domains/notifications'
export * from '@/api/domains/trends'
export * from '@/api/domains/discovery'
